### ISSUE TITLE
how to use base64 ?

### ISSUE THREAD

**Issue by vinodhum** [Riron/ionic-img-viewer#12]
Hi,
image I am using sanitizer.bypassSecurityTrustUrl(sale.img) and it works fine
but when I add imageViewer directive it open new with broken image 
and error says WARNING: sanitizing unsafe URL value data:image/jpeg

**Comment by Riron** [comment]
Fixed by https://github.com/Riron/ionic-img-viewer/commit/efffb6aba53fb6f0d6eb758e9d8a5eb41cd7c7bd
