### ISSUE TITLE
Small picture in the viewer

### ISSUE THREAD

**Issue by alexdragneel** [Riron/ionic-img-viewer#122]
### Please provide you version information :
Dependency        |Version
------------------|-------
ionic2                  | 3.20.0
angular               | ^3.9.2
ionic-img-viewer | ^2.9.0

Hello,

I have two ionic projects and I have installed your plugin on the two projects in the same way.

In the first project: It's work well but in the second, the picture are small. Have you any idea why ? The image tag is identical too.

![image](https://user-images.githubusercontent.com/7541099/40774407-ce14eb22-64c5-11e8-8b3f-39ef633b5d28.png)

![image](https://user-images.githubusercontent.com/7541099/40773653-d0e488f0-64c3-11e8-8ca9-d7aa8858dd29.png)

Thanks. :)

**Comment by Riron** [comment]
Hello,

Could you share your code ? It's hard to guess what the problem could be as is.
Thanks

**Comment by alexdragneel** [comment]
Wich part ?
I use it like that: `<img class="image" alt="" src="{{ (UserProfil)?.picture }}" style="object-fit: cover;" imageViewer/>`

**Comment by mathritter** [comment]
I'm having the same problem, image shrinks instead zomming. Except I'm using ionic 3

**Comment by alexdragneel** [comment]
@mathritter Hello, I have check all my code and a css variable picture was the problem. Check to remove temporalily some of your css to search wich one is the probleme.

**Comment by mathritter** [comment]
I removed everything from app.scss, nothing happened, same behaviour
