### ISSUE TITLE
Plugin trowns an error on  build 

### ISSUE THREAD

**Issue by hitmacreed** [Riron/ionic-img-viewer#133]
Plugin trowns an error on  build 
```
 ./node_modules/ionic-img-viewer/dist/es2015/src/image-viewer-impl.js
Module not found: Error: Can't resolve 'rxjs/operators' in '/Users/quanticosolutions/Desktop/myseg/mobile/node_modules/ionic-img-viewer/dist/es2015/src'
resolve 'rxjs/operators' in '/Users/quanticosolutions/Desktop/myseg/mobile/node_modules/ionic-img-viewer/dist/es2015/src'
  Parsed request is a module
```

**Comment by hitmacreed** [comment]
had to adatp to my ionic version soo `npm install ionic-img-viewer@2.8.0 --save`

**Comment by snaveenpandi** [comment]
i have also same error

./node_modules/ionic-img-viewer/dist/es2015/src/image-viewer-impl.js
Module not found: Error: Can't resolve 'rxjs/Observable' in 'D:\naveen\demoionic\demoionic1\node_modules\ionic-img-viewer\dist\es2015\src'

**Comment by hitmacreed** [comment]
> i have also same error
> 
> ./node_modules/ionic-img-viewer/dist/es2015/src/image-viewer-impl.js
> Module not found: Error: Can't resolve 'rxjs/Observable' in 'D:\naveen\demoionic\demoionic1\node_modules\ionic-img-viewer\dist\es2015\src'

npm install ionic-img-viewer@2.8.0 --save
