### ISSUE TITLE
iOS & Android module export error when building

### ISSUE THREAD

**Issue by dragonfire1119** [Riron/ionic-img-viewer#18]
When I use ``ionic build android`` or ``ionic build ios`` the error for ``Module ''*'' has no exported member 'Wrapper_ImageViewerDirective'.`` comes up.

I looked at this issue #17 & it doesn't seem to be my error.

ionic-img-viewer: v1.1.5
Ionic Framework Version: 2.0.0-rc.3

**Comment by Riron** [comment]
Could you try `1.1.6` and tell me if you still experience the problem ?

**Comment by dragonfire1119** [comment]
@Riron Looks like it is fixed! I was thinking the ionic-img-viewer.ts was missing the directive export. I'm learning angular 2 so I wasn't for sure! LOL Thanks for fixing it! 👍

**Comment by vazad28** [comment]
1.1.6 is working for me too. Thanks Riron. Thank you for writing this code and making is available for people like me who can only dream to write something like this. Much appreciated.
