### ISSUE TITLE
Don't seems to work

### ISSUE THREAD

**Issue by DouDzZz** [Riron/ionic-img-viewer#19]
Hi there, 
It looks great, and I really want to use it.
Unfortunatly, when I import it, my app do not like it at all:
`main.js:28334Uncaught Error: Unexpected value 'IonicImageViewerModule' imported by the module 'AppModule'(…)`

```
Your system information:

Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.0-rc.1
Ionic CLI Version: 2.1.8
Ionic App Lib Version: 2.1.4
Ionic App Scripts Version: 0.0.37-5
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.4
Node Version: v7.2.0
Xcode version: Not installed

```

I hope you can help me !

Cheers

**Comment by DouDzZz** [comment]
I just tried with a new projet and it works fine, it might due to a precise version of my ionic project

**Comment by Riron** [comment]
Yeah sorry about that, I will add it to the Readme but AOT compilation only works with Ionic `RC.3` and beyond.
