### ISSUE TITLE
Styles are not included

### ISSUE THREAD

**Issue by nkalinov** [Riron/ionic-img-viewer#20]
First of all thanks for the great component!

Just wanted to mention that the styles (.css neither .scss) are included in the package.
Have I missed something or this is a "bug"?
Version 1.1.7

Everything is working OK when I integrated the [scss from the src folder](https://github.com/Riron/ionic-img-viewer/blob/master/src/image-viewer.scss)

**Comment by Riron** [comment]
What do you mean not included in the package ? There is no `image-viewer.scss` file in your `node_modules/ionic-img-viewer/src/` folder ?
I'll have a look at it, but the file seems to be present on the npm repository as you can [see here](https://unpkg.com/ionic-img-viewer@1.1.7/dist/src/)

**Comment by nkalinov** [comment]
Ah, I've missed that - thanks!
Probably it would be helpful to put this in the README.

**Comment by Riron** [comment]
You mean that you had to manually import the SCSS file ? Normally this should have been automatic - if Ionic finds a file with the same name as the component it links the two of them.

**Comment by nkalinov** [comment]
Yes, I had to import it manually, don't know why Ionic don't detect it.

**Comment by josuper** [comment]
@nkalinov  show me plz
