### ISSUE TITLE
Error when clicking on image with upgrading to RC 4

### ISSUE THREAD

**Issue by dragonfire1119** [Riron/ionic-img-viewer#23]
When I click on a image I get ``Error in :0:0 caused by: this.plt.registerListener is not a function`` this started happening when upgrading to RC 4.

```
Ionic Framework: ^2.0.0-rc.4
Ionic Native: 2.2.11
Ionic App Scripts: 0.0.47
Angular Core: 2.2.1
Angular Compiler CLI: 2.2.1
Node: 6.9.1
```

**Comment by Riron** [comment]
Hi,
Are you using the latest version of the plugin ? Does the error message gives any more information ?

**Comment by dragonfire1119** [comment]
@Riron for some reason it's working now. One thing that I changed major was stop using yarn & go back to npm because ionic team doesn't recommend yarn. I guess that might be it?

**Comment by kctang** [comment]
I'm having similar issue but with RC5. I am not using yarn.

```
Cordova CLI: 6.3.1
Ionic Framework Version: 2.0.0-rc.5
Ionic CLI Version: 2.1.18
Ionic App Lib Version: 2.1.9
Ionic App Scripts Version: 1.0.0
ios-deploy version: 1.9.0
ios-sim version: 5.0.13
OS: OS X El Capitan
Node Version: v6.5.0
Xcode version: Xcode 8.2.1 Build version 8C1002
```

**Comment by Riron** [comment]
Thanks for reporting it,
I haven't tried RC5 yet, I will give it a look.

**Comment by Riron** [comment]
Indeed, there was a breaking change in RC5.
A PR fixing it should land today.

**Comment by kctang** [comment]
Thanks! Looking forward to test the fix for this.
