### ISSUE TITLE
Have to tap 3 time on Android to zoom

### ISSUE THREAD

**Issue by mparpaillon** [Riron/ionic-img-viewer#24]
Hi, great plugin !

I think there is an issue on tap to zoom on Android.
I have to tap 3 times to actually zoom the image.

Any idea ?

Thanks

**Comment by Riron** [comment]
Indeed I reproduced the problem and it should now be fixed with the latest `1.2.1` release 👍 
If after updating the problem persists feel free to comment on this issue.
Thanks again
