### ISSUE TITLE
[Feature] Be able to pinch to zoom?

### ISSUE THREAD

**Issue by dragonfire1119** [Riron/ionic-img-viewer#26]
I was wondering if this would be possible or if you have thought about it? Some of my users are thrown off to the fact of having to double tap the image.

**Comment by Riron** [comment]
I definitely thought about it, and i'll try to add it shortly 👍

**Comment by dragonfire1119** [comment]
Hello @Riron I know have probably been busy but I wanted to ask if you maybe have a ETA on this feature? Thanks for the hard work & time!

**Comment by Riron** [comment]
Hi, yeah sorry I don't have a lot of time actually.
The feature is nearly ready, you can find the code on the [pinch branch](https://github.com/Riron/ionic-img-viewer/tree/pinch). I just have to test it a little more before releasing it, so it should ship in a few days !

**Comment by dragonfire1119** [comment]
@Riron I completely understand no worries! I'll definitely be testing it! Thanks! 👍 If you have a feature or anything. I can test it on one of my projects as well!

**Comment by dragonfire1119** [comment]
@Riron It's working great so far on my testing! I see you also fixed the back button overlay which is a nice plus! Thanks!

**Comment by Riron** [comment]
Thanks a lot for the help and support, it's really good to hear :+1: 
I just released the `1.2.2` version, including the change. Please tell me if anything doesn't work as planned !
Thanks !
