### ISSUE TITLE
Ionic 2 RC5 not working

### ISSUE THREAD

**Issue by pavel-kurnosov** [Riron/ionic-img-viewer#28]
Module is not working with latest ionic rc5 version.

**Comment by Riron** [comment]
Hi, as it's working in existing RC5 applications, could you please give some more details ?
Any error in the console maybe ?
Thanks.

**Comment by pavel-kurnosov** [comment]
Hi, 
Sorry, did test again - in the morning - all was fine... Strange... But Thanks for plugin. :)
