### ISSUE TITLE
[BUG] In iOS the Status Bar overlapps Back button

### ISSUE THREAD

**Issue by GerardSoleCa** [Riron/ionic-img-viewer#29]
Hello,

Nice work.

I'm testing it on iOS and I'm seeing that the Back button is partially overlapped with the status bar, so only half of the button is clickable (half of height).

On the following image you can see the overlapping.

![screen shot 2017-01-30 at 14 11 05](https://cloud.githubusercontent.com/assets/2593956/22424244/00078c56-e6f6-11e6-8487-4d2a7fd1277f.png)

Thanks!

**Comment by Riron** [comment]
Thanks for the report !
I'll give it a look.

**Comment by rnarian** [comment]
I just ran into the same issue. Any update on this yet?

**Comment by Riron** [comment]
The fix [is ready](https://github.com/Riron/ionic-img-viewer/commit/b976f3f4f0f5b8c841aedf25336982bcedbd0506) and will be released in the upcoming days.

**Comment by Riron** [comment]
Fixed by https://github.com/Riron/ionic-img-viewer/pull/35/commits/b976f3f4f0f5b8c841aedf25336982bcedbd0506
