### ISSUE TITLE
Support Ionic RC 0

### ISSUE THREAD

**Issue by gfviegas** [Riron/ionic-img-viewer#3]

**Comment by danielehrhardt** [comment]
Hi i get this problem when i import ionic-img-viewer:
![image](https://cloud.githubusercontent.com/assets/19570043/18976386/cac52818-86b1-11e6-802a-6ba2870add5e.png)

![image](https://cloud.githubusercontent.com/assets/19570043/18976397/d41a362e-86b1-11e6-99d0-fe8296a5b2c5.png)

**Comment by gfviegas** [comment]
Im having the same issue @danielehrhardt

**Comment by Riron** [comment]
Hi and thanks for opening an issue,
Support for RC-0 is planned and will ship shortly.
Stay tuned !

**Comment by danielehrhardt** [comment]
@Riron is der anything new?

**Comment by Riron** [comment]
Hi, sorry for the delay.
Fixed by https://github.com/Riron/ionic-img-viewer/pull/6

**Comment by dmastag** [comment]
Awesome, would you mind explaining how to implement it?
I am having a hard time doing so.

**Comment by danielehrhardt** [comment]
Same Problem here!!
