### ISSUE TITLE
Make it compatible with Ionic 2.0.0

### ISSUE THREAD

**Issue by SidMorad** [Riron/ionic-img-viewer#33]
I assume latest version(1.2.1) is not compatible with Ionic 2.0.0 and later, please correct me if I am wrong.

So any plan to make it compatible (any time soon)?

Thank you for the great component by the way! :+1: 

p.s. According to README file we need to add `ImageViewerDirective` to `@Component` with `directives` attribute, but there is no `directives` attribute in `@Component` any more, is there any other way to use current directive? (in ionic 2.0.0)

**Comment by Riron** [comment]
Hi, glad you like it !

Quoting the README:

```
For Ionic 2 RC.0 and later:

import { IonicImageViewerModule } from 'ionic-img-viewer';

@NgModule({
  imports: [
    IonicImageViewerModule
  ]
})
export class AppModule {}
```

You only need the component attributes if you use a beta version of Ionic (back then Angular had directives in `@Component`). So it does already work with the latest Ionic :smile: 

The you can use it as follow in your templates:
```
<img src="IMAGE_URL" imageViewer />
```

Hope it helps !

**Comment by SidMorad** [comment]
ِYou are right, the config works with latest Ionic (as explained in the README file).

My issue was: I was testing it against an Embed Base64-Encoded image like following:
`
<img [src]="'data:' + item.pictureContentType + ';base64,' + item.picture" imageViewer />
`
Which is not working in my testing environment(Android 5.1.1).

Could we use this directive for Embed Base64-Encoded images?

Thank you! :-)

**Comment by Riron** [comment]
Ah OK :)
The library should already support base64 images, so could you give some more details about what your problem is ? A console error maybe ?
Thanks ! :+1:

**Comment by SidMorad** [comment]
Well it seems I was wrong again!
This morning things are working as expected, no problem in showing embed base64 images.

This time I notice the scroll feature is not working correctly after zooming a picture.(According to my experience, I might be wrong in this one too! ;-))
Scroll works only in vertical direction and not working in horizontal direction. My current app is using RTL feature:`<html dir="rtl">`  which is causing this issue. Maybe there is a workaround for this? perhaps forcing LTR direction for this component? obviously this component inherit the direction from the app, in best scenario I would like to do nothing in my side, and in the other side this component handles the trouble for me! ;-) 

This will be minor issue for me, and will not stop me from using this great/handy directive! :+1:
