### ISSUE TITLE
Compatibility with Ionic 2.2.0 

### ISSUE THREAD

**Issue by metz0r** [Riron/ionic-img-viewer#36]
Running 1.2.2 works fine on ionic 2.1.0, however after upgrading to ionic 2.2.0 (which has a newer angular 2 version):

`ionic build` works fine
`ionic build --prod` generates this error:

```
ionic-app-scripts 1.1.4
build prod started ...
clean started ...
clean finished in 4 ms
copy started ...
ngc started ...
build prod failed: Error encountered resolving symbol values statically. Calling function 'makeDecorator',
            function calls are not supported. Consider replacing the function or lambda with a reference to an exported
            function, resolving symbol NgModule in /node_modules/ionic-img-viewer/node_modules/@angular/core/src/metadata/ng_module.d.ts
...
```

**Comment by absolutsoul** [comment]
+1

**Comment by Riron** [comment]
Indeed, I just reproduced the bug.
Thanks a lot, a FIX will arrive shortly !

**Comment by Riron** [comment]
Fixed in https://github.com/Riron/ionic-img-viewer/commit/6a064e56303b49d77e5b454ac0f17ffc0bd93116 
A new release (`1.3.0`) has been done.

Thanks for reporting the bug !
