### ISSUE TITLE
Production build Issue

### ISSUE THREAD

**Issue by bonoadil** [Riron/ionic-img-viewer#39]
Can't build in production mode, Any idea ?:
Log :

`[10:47:39]  ionic-app-scripts 1.1.4 
[10:47:39]  build prod started ... 
[10:47:39]  clean started ... 
[10:47:39]  clean finished in 2 ms 
[10:47:39]  copy started ... 
[10:47:39]  ngc started ... 
[10:47:41]  build prod failed: Error encountered resolving symbol values statically. Calling function 'makeDecorator', 
            function calls are not supported. Consider replacing the function or lambda with a reference to an exported 
            function, resolving symbol NgModule in 
            /Users/Adil/IdeaProjects/aliae/node_modules/ionic-img-viewer/node_modules/@angular/core/src/metadata/ng_module.d.ts,
            resolving symbol NgModule in 
            /Users/Adil/IdeaProjects/aliae/node_modules/ionic-img-viewer/node_modules/@angular/core/src/metadata.d.ts, 
            resolving symbol NgModule in 
            /Users/Adil/IdeaProjects/aliae/node_modules/ionic-img-viewer/node_modules/@angular/core/src/core.d.ts, 
            resolving symbol NgModule in 
            /Users/Adil/IdeaProjects/aliae/node_modules/ionic-img-viewer/node_modules/@angular/core/index.d.ts, 
            resolving symbol IonicImageViewerModule in 
            /Users/Adil/IdeaProjects/aliae/node_modules/ionic-img-viewer/dist/src/module.d.ts, resolving symbol 
            IonicImageViewerModule in /Users/Adil/IdeaProjects/aliae/node_modules/ionic-img-viewer/dist/src/module.d.ts 
[10:47:41]  ionic-app-script task: "build" 
[10:47:41]  Error: Error encountered resolving symbol values statically. Calling function 'makeDecorator', function 
            calls are not supported. Consider replacing the function or lambda with a reference to an exported function, 
            resolving symbol NgModule in 
            /Users/Adil/IdeaProjects/aliae/node_modules/ionic-img-viewer/node_modules/@angular/core/src/metadata/ng_module.d.ts,
            resolving symbol NgModule in 
            /Users/Adil/IdeaProjects/aliae/node_modules/ionic-img-viewer/node_modules/@angular/core/src/metadata.d.ts, 
            resolving symbol NgModule in 
            /Users/Adil/IdeaProjects/aliae/node_modules/ionic-img-viewer/node_modules/@angular/core/src/core.d.ts, 
            resolving symbol NgModule in 
            /Users/Adil/IdeaProjects/aliae/node_modules/ionic-img-viewer/node_modules/@angular/core/index.d.ts, 
            resolving symbol IonicImageViewerModule in 
            /Users/Adil/IdeaProjects/aliae/node_modules/ionic-img-viewer/dist/src/module.d.ts, resolving symbol 
            IonicImageViewerModule in /Users/Adil/IdeaProjects/aliae/node_modules/ionic-img-viewer/dist/src/module.d.ts 
Error: Error encountered resolving symbol values statically. Calling function 'makeDecorator', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol NgModule in /Users/Adil/IdeaProjects/aliae/node_modules/ionic-img-viewer/node_modules/@angular/core/src/metadata/ng_module.d.ts, resolving symbol NgModule in /Users/Adil/IdeaProjects/aliae/node_modules/ionic-img-viewer/node_modules/@angular/core/src/metadata.d.ts, resolving symbol NgModule in /Users/Adil/IdeaProjects/aliae/node_modules/ionic-img-viewer/node_modules/@angular/core/src/core.d.ts, resolving symbol NgModule in /Users/Adil/IdeaProjects/aliae/node_modules/ionic-img-viewer/node_modules/@angular/core/index.d.ts, resolving symbol IonicImageViewerModule in /Users/Adil/IdeaProjects/aliae/node_modules/ionic-img-viewer/dist/src/module.d.ts, resolving symbol IonicImageViewerModule in /Users/Adil/IdeaProjects/aliae/node_modules/ionic-img-viewer/dist/src/module.d.ts
    at SyntaxError.BaseError [as constructor] (/Users/Adil/IdeaProjects/aliae/node_modules/@angular/compiler/bundles/compiler.umd.js:1597:31)
    at new SyntaxError (/Users/Adil/IdeaProjects/aliae/node_modules/@angular/compiler/bundles/compiler.umd.js:1795:20)
    at simplifyInContext (/Users/Adil/IdeaProjects/aliae/node_modules/@angular/compiler/bundles/compiler.umd.js:25783:27)
    at StaticReflector.simplify (/Users/Adil/IdeaProjects/aliae/node_modules/@angular/compiler/bundles/compiler.umd.js:25795:17)
    at StaticReflector.annotations (/Users/Adil/IdeaProjects/aliae/node_modules/@angular/compiler/bundles/compiler.umd.js:25291:64)
    at NgModuleResolver.resolve (/Users/Adil/IdeaProjects/aliae/node_modules/@angular/compiler/bundles/compiler.umd.js:17771:86)
    at CompileMetadataResolver.getNgModuleMetadata (/Users/Adil/IdeaProjects/aliae/node_modules/@angular/compiler/bundles/compiler.umd.js:18272:64)
    at addNgModule (/Users/Adil/IdeaProjects/aliae/node_modules/@angular/compiler/bundles/compiler.umd.js:25053:62)
    at /Users/Adil/IdeaProjects/aliae/node_modules/@angular/compiler/bundles/compiler.umd.js:25064:18
    at Array.forEach (native)

npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/Cellar/node/6.7.0/bin/node" "/Users/Adil/.npm-packages/bin/npm" "run" "ionic:build" "--" "--prod"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! aliae@ ionic:build: `ionic-app-scripts build "--prod"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the aliae@ ionic:build script 'ionic-app-scripts build "--prod"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the aliae package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ionic-app-scripts build "--prod"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs aliae
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls aliae
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Adil/IdeaProjects/aliae/npm-debug.log`

Dependencies  : 
"dependencies": {
    "@angular/common": "2.4.8",
    "@angular/compiler": "2.4.8",
    "@angular/compiler-cli": "2.4.8",
    "@angular/core": "2.4.8",
    "@angular/forms": "2.4.8",
    "@angular/http": "2.4.8",
    "@angular/platform-browser": "2.4.8",
    "@angular/platform-browser-dynamic": "2.4.8",
    "@angular/platform-server": "2.4.8",
    
    "ionic-angular": "2.3.0",
    "@ionic-native/core": "3.1.1",
    "@ionic-native/status-bar": "3.1.1",
    "@ionic-native/splash-screen": "3.1.1",
    "@ionic-native/network": "3.1.1",
    "@ionic-native/keyboard": "3.1.1",
    "@ionic-native/push": "3.1.1",
    "@ionic/storage": "2.0.0",
    "ionicons": "3.0.0",
    
    "ionic-img-viewer": "1.1.8",
    "rxjs": "5.0.1",
    "zone.js": "0.7.2",
    "sw-toolbox": "3.4.0"
  },
  "devDependencies": {
    "@ionic/app-scripts": "1.1.4",
    "typescript": "2.0.9"
  }

**Comment by Riron** [comment]
Try to update to `ionic-img-viewer v1.3.0`.
I haven't tried `ionic-angular v2.3.0` with the library yet, i'll do it later on today and publish a fix if needed.

**Comment by bonoadil** [comment]
Thank you, that's works. but why this version is not on git repo releases.

**Comment by Riron** [comment]
Yes the github tags were not up to date - i will correct that.
Thats for pointing this out to my attention. Meanwhile, you can refer to npm to see the latest version.

**Comment by uzumakinaruto123** [comment]
Hii @Riron   , I am facing this on latest version of `ionic-img-viewer`

```
"ionic-img-viewer": "^1.3.2",
"ionic-angular": "2.0.1",
```

any fix ? 

Thanks.

**Comment by Riron** [comment]
Same error on production builds only ? Version `1.3.2` is not valid with `"ionic-angular": "2.0.1"`.
With `"ionic-angular": "2.3.0"` it's been tested and shoulds work. Please make sure you upgraded `ionic-angular` correctly, and if the problem persist please open a new issue 😉 
Thanks !

**Comment by uzumakinaruto123** [comment]
Yes , I upgraded and verified it in node_modules. Here is the issue [https://github.com/Riron/ionic-img-viewer/issues/43](https://github.com/Riron/ionic-img-viewer/issues/43)
