### ISSUE TITLE
Image click passes click event to list item

### ISSUE THREAD

**Issue by uzumakinaruto123** [Riron/ionic-img-viewer#40]
Thanks for the module. nice one.
Only one issue , on clicking image it passes the event to list item and app navigates. event should be prevented.

**Comment by Riron** [comment]
Thanks for the report ! I will give it a look and release a fix soon.

**Comment by Riron** [comment]
Hi,
I couldn't quite reproduce the problem. Could you provide a small code sample of what you are doing ?
I suppose the images are list items, and clicking on the item should so some sort of actions but clicking on the image itself should not trigger this action ?
A small piece of your html would definitely help understand better the problem.
Thanks 👍

**Comment by uzumakinaruto123** [comment]
Here is the code , a normal list with list item having thumbnail on left similar to one in ionic docs :- 

```
<ion-list>
    <ion-item class="listItem" *ngFor="let item of d.items | search:d.searchvalue" (click)="openItem(item)">
      <ion-thumbnail item-left>
        <img src="{{item.resimage}}" imageViewer src-fallback="{{ (item.Nid % 2 == 0)? 'assets/img/default1.jpg':'assets/img/default2.jpg'}}">
      </ion-thumbnail>
      <h2 [innerHTML]="item.Title"></h2>
      <p [innerHTML]="item.Description"></p>
      <p>Discount : {{item.Discount}}%</p>
    </ion-item>
  </ion-list>
```

Here everything works , except when that thumbnail is clicked , it also triggers **(click)="openItem(item)"** 

In which , page is navigated to item detail page. Thanks

**Comment by uzumakinaruto123** [comment]
wow that was fast ! Thanks :) will update
