### ISSUE TITLE
Compatibility with ionic 2.3.0

### ISSUE THREAD

**Issue by metz0r** [Riron/ionic-img-viewer#41]
Running ionic-img-viewer@1.3.0
ionic@2.3.0
(works with ionic@2.2.0)

`ionic build` - works
`ionic build --prod` - works up until  `uglifyjs finished in 21.99 s` - then silently hangs up

**Comment by Riron** [comment]
It should have been fixed in `v1.3.1` release. 
Please feel free to comment in this issue if you still experience the problem.
