### ISSUE TITLE
Not Working for Image In Google Map Info Window

### ISSUE THREAD

**Issue by adevoid** [Riron/ionic-img-viewer#44]
I can get the imageViewer to work in a .html file of an Ionic 2 app I'm building, but it is not working in a .ts file that I'm writing a google map info window in. No errors appear. When I click the image just nothing happens.

   ```
 let ContentPlace = `<img height="125" width="125" src=${this.a} imageViewer />`;
          var infoWindow = new google.maps.InfoWindow({
              content: " "
            });
      google.maps.event.addListener(marker2, 'click', () => {
      infoWindow.close();
      infoWindow.setContent(ContentPlace);
      infoWindow.open(this.map, marker2);
      });
        });
```
`this.a` is a base64 image.  I have tried wrapping it in quotation marks like so: `"${this.a}"`, but nothing.

Am I doing something wrong, or is this a limitation of ionic-img-viewer?

**Comment by Riron** [comment]
You are appending un-compiled angular-HTML to the DOM, it cannot work.
Have a look at the [dynamic component loader cookbook](https://angular.io/docs/ts/latest/cookbook/dynamic-component-loader.html), it should be helpful !
