### ISSUE TITLE
[enhancement] Android back button

### ISSUE THREAD

**Issue by Sogapp** [Riron/ionic-img-viewer#45]
Is it possible to handle the android back button? The idea is to keep the same behavior as the top left arrow.
Thanks for this great plugin!

**Comment by Riron** [comment]
Hi, i'm glad you like it 😄 
I thought the back button was already working, but maybe not - i'll check and correct if necessary !
Thanks for opening an issue.

**Comment by Sogapp** [comment]
Hi,
Thank for your answer. Did you check this issue?
I have tried to understand your code but I don't manage to link the android back button to closure of the popin

**Comment by Riron** [comment]
It should be working in the latest release 👍
