### ISSUE TITLE
Not showing right in the css. Things happening

### ISSUE THREAD

**Issue by FredrikHa** [Riron/ionic-img-viewer#46]
Hi!
I see in the html that things are happening when I tap an image, but its not showing. Something wrong with my css?

```
Cordova CLI: 6.4.0 
Ionic Framework Version: 2.0.1
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: 1.9.1 
ios-sim version: 5.0.13 
OS: macOS Sierra
Node Version: v6.9.2
Xcode version: Xcode 8.3.1 Build version 8E1000a
```

**Comment by FredrikHa** [comment]
For some reason, it works now.

Maybe because I placed `imageViewer` in the end of the `img` tag.

**Comment by Riron** [comment]
Hmm weird, what do you mean by placing `imageViewer` in the end of the `tag` ?
from
```
<img src="IMAGE_URL" imageViewer someOtherDirectiveOrAttribute />
```
to
```
<img src="IMAGE_URL" someOtherDirectiveOrAttribute imageViewer />
```
?

Anyway, glad it works now !

**Comment by FredrikHa** [comment]
Yes thats right, but it looks like that wasn't the issue.

Yeah, it works! Good job, looks nice 👍
