### ISSUE TITLE
ionic 3.1.0 support

### ISSUE THREAD

**Issue by metz0r** [Riron/ionic-img-viewer#48]
`ionic build`

[13:21:02]  transpile started ... 
[13:21:05]  typescript: node_modules/ionic-img-viewer/dist/src/image-viewer-transition-gesture.d.ts, line: 6 
            Type 'any' is not a constructor function type. 

       L5:  import { DomController } from 'ionic-angular';
       L6:  export declare class ImageViewerTransitionGesture extends PanGesture {
       L7:      private component;

**Comment by leoruhland** [comment]
The Ionic Team made some refactor in the code.. I opened a PR for that: https://github.com/Riron/ionic-img-viewer/pull/47

**Comment by Riron** [comment]
The PR has been merged, the release will follow tomorrow - I just need to do some minor tweaks before publishing it.

**Comment by Riron** [comment]
Version `2.1.0` is now published with the fix.
