### ISSUE TITLE
Type 'any' is not a constructor function type

### ISSUE THREAD

**Issue by vsrboth** [Riron/ionic-img-viewer#51]
node_modules/ionic-img-viewer/dist/src/image-viewer-transition-gesture.d.ts

export declare class ImageViewerTransitionGesture extends PanGesture {
    private component;
}

ionic2 v: 2.2.1

Thank you so much.

**Comment by Riron** [comment]
What version of `ionic-img-viewer` are you using ? You must use `v1.x` with ionic `v2.x`

**Comment by vsrboth** [comment]
Thank you. I was about to let you know 😄 

Thank you so much once again.

**Comment by vsrboth** [comment]
Thank you. I was about to let you know 😄 

Thank you so much once again.

**Comment by Riron** [comment]
So i assume that was the problem ? Closing the issue then !
You are welcome 😄
