### ISSUE TITLE
Installation warning

### ISSUE THREAD

**Issue by lsantaniello** [Riron/ionic-img-viewer#52]
Hi guys,
Installation shows the following warnings:

`npm install --save ionic-img-viewer
ionic-hello-world@ C:\projects\ionic\flannery
+-- UNMET PEER DEPENDENCY ionic-angular@2.0.0
`-- ionic-img-viewer@2.1.0

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.1.1
npm WARN ionic-img-viewer@2.1.0 requires a peer of ionic-angular@~3.1.0 but none was installed.`

When I run my app I receive this error:

Typescript Error
Type 'any' is not a constructor function type.
...nery/node_modules/ionic-img-viewer/dist/src/image-viewer-transition-gesture.d.ts
import { DomController } from 'ionic-angular';
export declare class ImageViewerTransitionGesture extends PanGesture {
    private component;

Could you please help me?

Thanks

**Comment by Riron** [comment]
Indeed ! As npm is saying, `ionic-img-viewer@2.1.0 requires a peer of ionic-angular@~3.1.0 but none was installed`.
If you use `ionic-img-viewer@2.1.0` you need `ionic-angular@~3.1.0` - that's the point of peer dependencies, inform the user if there are version mismatchs.

If you use `ionic-angular@2.x.x` you'll need an earlier version of `ionic-img-viewer` (1.x.x).
