### ISSUE TITLE
Update to the latest Ionic Framework?

### ISSUE THREAD

**Issue by dragonfire1119** [Riron/ionic-img-viewer#56]
When I installed the new version of Ionic Framework it gave me a ``UNMET PEER DEPENDENCY ionic-angular@3.3.0`` because you have it at 3.1.0.

**Comment by Riron** [comment]
Indeed I haven't had time yet, i'll do it later this week !

**Comment by dragonfire1119** [comment]
@Riron Thanks for your time on this. I know time is hard to come by sometimes with my world as well!

**Comment by Alb93** [comment]
Same here, awaiting Mr. Riron :)

**Comment by hexufeng** [comment]
you can try to change all the dependency's version as the same with this project!

**Comment by Alb93** [comment]
Nothing new here?

**Comment by Riron** [comment]
`v2.3.0` has been released and should support `ionic-angular@3.3.0`.
If you experience any problem, please open an issue.

Thanks !
