### ISSUE TITLE
Not working on ionic 3.3.0/angular 4.1.2

### ISSUE THREAD

**Issue by JulianGarciaCastillo** [Riron/ionic-img-viewer#61]
Sofware version:
- Ionic : 3.3.0
- Angular: 4.1.2

I can't make this plugin work. Touch the image and nothing happen.
I'm using it like this:

.ts
`import { IonicImageViewerModule } from 'ionic-img-viewer';`
```
@NgModule({
  imports: [
    IonicImageViewerModule
  ]
})
```
.html
```
<ion-header id="header-controls"><ion-navbar> <ion-title>
   <span>{{device.name}}</span>
</ion-title> </ion-navbar></ion-header>

<ion-content class="card-background-page" id="content-page">
  <img [src]="'https://url-image.jpg'" imageViewer />
</ion-content>
```

*It's kind of confusing that the plunker demo you provide and the instructions are different, using IonicImageViewerModule and ImageViewerDirective to be imported.
Thank you!

**Comment by dragonfire1119** [comment]
Currently the module does not work on 3.3.0 #56 

If this did work with your version you would need to use ``IonicImageViewerModule``. 

If your using lazy loading you would need to have it in your {page}.module.ts instead of app.module.ts. It says on the README For Ionic 2 RC.0 and later => ``IonicImageViewerModule``.

**Comment by Riron** [comment]
Please upgrade to `ionic-img-viewer@2.3.0` to see if it fixes your problem.
This new version should have support for `ionic-angular@3.3.0`.

**Comment by Riron** [comment]
And yes indeed the plunkr is outdated, I will update it. But it's rather a demo than a "how to" 😉

**Comment by Alb93** [comment]
In my case @Riron's update works well. But I still have a problem. Nothing happen on click when the image is inside a super-tab page [https://github.com/zyra/ionic2-super-tabs](url). Some advices?

**Comment by Riron** [comment]
@Alb93 please open a separate issue with some more details. Thanks !
