### ISSUE TITLE
Nothing happen when imageViewer is placed inside a super-tab page

### ISSUE THREAD

**Issue by Alb93** [Riron/ionic-img-viewer#62]
Hi!

I use super-tabs elements in this way: 

` <super-tabs >
    <super-tab [rootParams]="subcategory" [swipeBackEnabled]="false" [root]="page1" [title]="showTitles? 'Immagine' : ''" [icon]="showIcons? 'image': ''" id="page1"></super-tab>
    <super-tab [rootParams]="subcategory" [root]="page2" [title]="showTitles? 'Descrizione' : ''" [icon]="showIcons? 'clipboard' : ''" id="page2"></super-tab>
   </super-tabs>`

The component is similar to the classical tabs in ionic. Specifications can be found here: [https://github.com/zyra/ionic2-super-tabs](url).

Well, one of this page(page1) is like 
`<ion-content>
  <ion-card>
<img imageViewer [src]="subcategory.image_url"/>
</ion-card>
</ion-content>`

but nothing happen on click. Instead all is fine out of this component.

Running ionic info:

global packages:

    @ionic/cli-utils : 1.3.0
    Cordova CLI      : 7.0.1
    Ionic CLI        : 3.3.0

local packages:

    @ionic/app-scripts              : 1.3.7
    @ionic/cli-plugin-cordova       : 1.3.0
    @ionic/cli-plugin-ionic-angular : 1.3.0
    Cordova Platforms               : android 6.2.3 browser 4.1.0
    Ionic Framework                 : ionic-angular 3.3.0

System:

    Node       : v7.10.0
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed

**Comment by sebastianovide** [comment]
did you work around it ?

**Comment by Alb93** [comment]
Nope. Switching to [https://github.com/sarriaroman/photoviewer](url) has been my solution.

**Comment by Riron** [comment]
Do you have the same problem @sebastianovide ?
I didn't have time to reproduce the bug yet, I'll probably do it this week. But the new way of opening the viewer (trigger through code) [landing shortly](https://github.com/Riron/ionic-img-viewer/issues/42#issuecomment-309685435) might help with that.

**Comment by Riron** [comment]
Code trigger is now available in `ionic-img-viewer@2.4.0`. Maybe that can help 😄

**Comment by Riron** [comment]
@Alb93 I just tried your `ionic2-super-tabs` setup  and it's working as expected on my laptop... You don't have any error in the console ?

@sebastianovide do you have the exact same problem ?

**Comment by dkd051** [comment]
I have same problem. I am using ionic2-super-tabs too. [http://i.imgur.com/T1oZg3s.png](url)
Gesture is working but no show.

**Comment by dkd051** [comment]
suddenly It works very well even I didn't do anything.
