### ISSUE TITLE
how to set a listener for image viewer closing ?

### ISSUE THREAD

**Issue by shareef1989** [Riron/ionic-img-viewer#63]
I want to run some function after closing the image viewer , so how to catch that event ?

**Comment by Riron** [comment]
It's not yet possible, but I like the idea.
I will work on it ASAP.

**Comment by shareef1989** [comment]
Ok , thank you

**Comment by Riron** [comment]
Closing this issue as it landed in `ionic-img-viewer@2.4.0`.
