### ISSUE TITLE
Unable to swipe when using img viewer inside an ion-slide

### ISSUE THREAD

**Issue by hamzatrq** [Riron/ionic-img-viewer#64]
Greeting. I was trying to use the plugin inside an ion-slide component. But I am not able to swipe now. It will be a lot convenient if we can call a function on an event like (click)="openimage(imgUrl)" to trigger the plugin.

**Comment by Riron** [comment]
You mean that the swipe triggers a `click` event, and that the image opens in full screen mode ?

It will be possible to open it like you said in the next release.

**Comment by QXCgxNED** [comment]
I'd like to add my voice to this. I am also using image viewer inside Ionic Slides component.

I am able to slide, but I am stuck with default configuration. For example, I do not like I have to swipe up to close the viewer. This is bad UX, if you tapped to go in, you should tap to go out. But I cannot change it without source code changed.

If image viewer would be opened using onClick event, then in addition to the URL parameter we could also specify the "options" parameter. And in the options it could be anything: behaviour, colours, you name it, we could expand it indefinitely.

The image viewer is great, thank you Riron. It's probably the best I've tried so far, and supports both mobile and desktop. But it's too rigid at the moment, it needs an easy way to be configured and extended.

Using onClick event and options parameter is one way to do it, if there's a better way I'm all for it too.

**Comment by Riron** [comment]
@QXCgxNED swiping does work for you ? I haven't reproduced the bug yet.

And calling the viewer throuh code is now possible in `ionic-img-viewer@2.4.0`.

**Comment by hamzatrq** [comment]
@QXCgxNED I have tried using image viewer inside ionic slides but was not able to swipe afterward can you please share your implementation?

**Comment by QXCgxNED** [comment]
I am really not doing anything special, it's actually pretty raw at the moment, could be improved.

`<ion-content>
	<ion-header>
		[...]
	</ion-header>

	<ion-slides>
		<ion-slide *ngIf="user.Picture1 == 1">
			<img src="{{user.ImgSrc1}}" imageViewer />
		</ion-slide>
		<ion-slide *ngIf="user.Picture2 == 1">
			<img src="{{user.ImgSrc2}}" imageViewer />
		</ion-slide>
		[...]
	</ion-slides>
</ion-content>`

**Comment by Riron** [comment]
I tried as well with [the classic implementation](http://ionicframework.com/docs/components/#slides) and it works as expected.

@hamzatrq can you share your implementation ?

**Comment by nisharai11** [comment]
Hi @Riron  and @QXCgxNED , i am not being able to slide the viewed image using imageViewer. i tried the following:
<ion-grid>
 <ion-row>
  <ion-col col-6 col-md-4 col-xl-3 *ngFor="let photo of (galleryDetails | async)?.messageBody">
   <ion-slides>
    <ion-slide>
     <div *ngIf="photo.contentType === 'Images'" class="swiper-zoom-container">
      <img src="{{ serverName + photo.contentUrl }}" class="image-container" imageViewer/>
     </div>
    </ion-slide>
   </ion-slides>
  </ion-col>
 </ion-row>
</ion-grid>
it allows only single view and the slide is happening when the image is not viewed.
Any help would be appreciated.
Thank you.

**Comment by Riron** [comment]
Your HTML looks weird at first sight. You are repeating the whole `<ion-slides>`, not the `<ion-slide>`. Notice the `s` - try to make sure your code work without the `imageViewer` directive at first

**Comment by nisharai11** [comment]
When i don't repeat the slides, the image gets stacked up in one column only. My requirement is to display the pictures in a grid and when the user clicks a particular image, they should be able to slide the next image from there itself without having to go back and clicking again.
