### ISSUE TITLE
Image viewer is not working when use innerHTML property

### ISSUE THREAD

**Issue by yuvarajuv** [Riron/ionic-img-viewer#66]
Image viewer is not working when i bind img tags dynamically using innerHTML property

**Comment by Riron** [comment]
This is not a bug as you cannot insert an element as row HTML, Angular has to compile it.

If you want to dynamically add components into your page, have a look at [the Angular guide on that topic](https://angular.io/guide/dynamic-component-loader).

Hope it helps !
