### ISSUE TITLE
Not able to add in ionic2.0

### ISSUE THREAD

**Issue by Anshdesire** [Riron/ionic-img-viewer#7]
How to use this directive. Added in declarations: [...] but not ale ti get on respective page ?

If you have any demo code or suggestion . Please share.

**Comment by kadox07** [comment]
it's true! I have the same problem too. I entered in "decleration" Directive but does not work. I use ionic 2.0 RC0. Help me

**Comment by danielehrhardt** [comment]
same here

**Comment by Riron** [comment]
Sorry about that, the [README](https://github.com/Riron/ionic-img-viewer/blob/master/README.md) has been updated with up to date instructions.

**Comment by imanube** [comment]
Where do you import it for @ngModule? is it the file app.module.ts? and if it is i keep getting an error 

Error: Can't resolve all parameters for ImageViewerComponent: (GestureController, ElementRef, NavController, NgZone, Renderer, ?, Platform, NavParams, Config, DomSanitizer).
any ideas?

**Comment by Riron** [comment]
Please open a new issue if you experience a problem - and make sure you use the right version of `ionic-img-viewer` for your version of `ionic-angular` (eg: `ionic-img-viewer 1.3.2` is for `ionic-angular ^2.2.0`).
Thanks.
