### ISSUE TITLE
Feature Request: Add custom Css Class to image shown in Preview

### ISSUE THREAD

**Issue by HartHerbert** [Riron/ionic-img-viewer#70]
Hey and thanks for the awesome component!

I just wanted to ask if you could implement that a custom css class could be added to the image ? 
Because I display a Css-filter over the images and when I open your preview component I can not send a custom class with. 

Would be awesome.

**Comment by Riron** [comment]
Yeah why not, seems like a legit use case. I'll add it to the next release 😉

**Comment by HartHerbert** [comment]
thanks, appreciate it
