### ISSUE TITLE
facing issue gesture and any 

### ISSUE THREAD

**Issue by Anujmoglix** [Riron/ionic-img-viewer#71]
Runtime Error
Cannot find module "ionic-angular/gestures/pan-gesture"

![image](https://user-images.githubusercontent.com/26056096/27764975-24de5a96-5ec4-11e7-961c-b2489795d0c2.png)

**Comment by Riron** [comment]
Please provide your version information (Ionic, angular & ionic-img-vierwer).
Thanks

**Comment by Anujmoglix** [comment]
Hi, You replied after many days so i have used modal on click for image .

**Comment by AntonioMenti** [comment]
Same issue, any solutions?

**Comment by ravisojitra** [comment]
Even i have the same issue.... please can you help?

**Comment by sharkoz** [comment]
> Please provide your version information (Ionic, angular & ionic-img-viewer).

**Comment by ravisojitra** [comment]
hi there, i solved that issue but now i am facing new issue at line no. 2 and 3 in image-viewer.d.ts which is 

```
import { Overlay } from "ionic-angular/navigation/overlay";
import { OverlayProxy } from "ionic-angular/navigation/overlay-proxy";
```
There i folder named navigation in ionic-angular inside node_modules but it doesn't contain overlay and overlay-proxy files.

i tried downloading it but couldn't find it from anywhere.

Ionic info:


 ordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.5
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 7
Node Version: v6.10.2
Xcode version: Not installed


angular version : 2.2.1

ionic-img-viewer : latest

**Comment by sharkoz** [comment]
If you found a solution you can post it there, but if you have another error please open a new issue. Thanks ! :+1:
