### ISSUE TITLE
Closing the viewer programmatically 

### ISSUE THREAD

**Issue by shareef1989** [Riron/ionic-img-viewer#73]
in the beginning , I have to say big thank for you. You give us very useful update that let us catching closing event.

For now, I would like to know if there is a way to close the img-viewer using code!

Could I ?

**Comment by Riron** [comment]
Glad you like it !
Yeah that seems like a legit use case, I'll try to add it to the next release 😉

**Comment by Riron** [comment]
You can use now use `viewer.dismiss()`. eg:
```
const viewer = this.imageViewerCtrl.create(imageToView)
viewer.present();
    
setTimeout(() => viewer.dismiss(), 1000);
```
