### ISSUE TITLE
please show me simple code use with innerHTML

### ISSUE THREAD

**Issue by kh71** [Riron/ionic-img-viewer#76]
### Please provide you version information :
Dependency      |Version
----------------|-------
ionic2          | 3.5
angular         | 2
ionic-img-viewer| 2.4.0

### Have you checked...
- [y] That npm install returns no warning ?
- [y] Doing a purge of your node_modules folder ?

i'm beginner not clear directive. please help me

**Comment by Riron** [comment]
Hi, this is not a question about the plugin itself but about Angular. 

InnerHtml does not compile components as needed by Angular, so it doesn't work with anything else than regular HTML.
You have plenty of examples in the doc, even a dedicated guide about the [Dynamic component loader](https://angular.io/guide/dynamic-component-loader).
