### ISSUE TITLE
UNMET PEER DEPENDENCY ionic 3.5.2 and 3

### ISSUE THREAD

**Issue by chukwu** [Riron/ionic-img-viewer#77]
UNMET PEER DEPENDENCY ionic-angular@3.5.2
└── ionic-img-viewer@2.4.0

I think you need to update it. Its not working for my project.

### Please provide you version information :
Dependency      |Version
----------------|-------
ionic2          | 3.5.0
angular         | 3.5.3
ionic-img-viewer| 2.4.0

### Have you checked...
- [ ] That npm install returns no warning ?
- [ ] Doing a purge of your node_modules folder ?

**Comment by netsesame2** [comment]
It just a warning.... no more need to care.

**Comment by Riron** [comment]
Indeed I have to update the package, I'll do it quickly.

**Comment by godspeed529** [comment]
I am confused here.  I am getting the "UNMET PEER DEPENDENCY" error/warning.  

1. Is this an error or a warning?
2. Does ionic-img-viewer@2.4.0  support ionic-angular@3.5.x?

├── UNMET PEER DEPENDENCY ionic-angular@3.5.3
└── ionic-img-viewer@2.4.0 

npm WARN ajv-keywords@2.1.0 requires a peer of ajv@>=5.0.0 but none was installed.
npm WARN ionic-img-viewer@2.4.0 requires a peer of ionic-angular@~3.4.0 but none was installed.
Mashamas-MacBook-Pro:moxility-ionic mashama$ ionic info

global packages:

    @ionic/cli-utils : 1.5.0
    Cordova CLI      : 6.5.0 
    Ionic CLI        : 3.5.0

local packages:

    @ionic/app-scripts              : 2.0.2
    @ionic/cli-plugin-cordova       : 1.4.1
    @ionic/cli-plugin-ionic-angular : 1.3.2
    Cordova Platforms               : android 6.1.2 browser 4.1.0 ios 4.3.1
    Ionic Framework                 : ionic-angular 3.5.3

System:

    Node       : v7.7.4
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b 
    ios-deploy : 1.9.1 
    ios-sim    : 5.0.13 
    npm        : 4.1.2

**Comment by godspeed529** [comment]
@Riron I just noticed your comment from an hour ago ... is it ok to assume that your updates to the package.json will resolve my issue here?  I have yet to get this to work in my project.

**Comment by sharkoz** [comment]
@godspeed529 as mentioned earlier, it is just a warning. @Riron update will only make the warning disappear during `npm install`. 

Do you have any problem popping up _after_ the npm install ? If you do, please open another issue and describe it there ! :wink:

**Comment by godspeed529** [comment]
@sharkoz thanks for the clarification.  I will double back to this again soon as far as I can tell from your messaging this should work with the latest and greatest Ionic!  I have already tried twice before and can't seem to get it working in my project.  Perhaps this time I will try in a freshly generated 3.6.0 app ...
