### ISSUE TITLE
facing issue in overlay and overlay-proxy in image-viewer.d.ts

### ISSUE THREAD

**Issue by ravisojitra** [Riron/ionic-img-viewer#78]
hi there,  i am facing new issue at line no. 2 and 3 in image-viewer.d.ts which is

import { Overlay } from "ionic-angular/navigation/overlay";
import { OverlayProxy } from "ionic-angular/navigation/overlay-proxy";
There is folder named navigation in ionic-angular inside node_modules but it doesn't contain overlay and overlay-proxy files.

i tried downloading it but couldn't find it from anywhere.

Ionic info:

ordova CLI: 6.4.0
Ionic Framework Version: 2.0.0-rc.5
Ionic CLI Version: 2.2.1
Ionic App Lib Version: 2.2.0
Ionic App Scripts Version: 1.0.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 7
Node Version: v6.10.2
Xcode version: Not installed

angular version : 2.2.1

ionic-img-viewer : latest

**Comment by Riron** [comment]
The latest release does not work with `Ionic Framework Version: 2.0.0-rc.5`.
The easiest would be for you to update your Ionic to the latest release.

Otherwise, try `ionic-img-viewer@v1.2.1` but there will be feature missing compared to the actual version.
