### ISSUE TITLE
Sensitivity

### ISSUE THREAD

**Issue by afcruzs** [Riron/ionic-img-viewer#79]
Hi, is there any way to tune the sensitivity of the drag/pinch on the zoom?

Dependency      |Version
----------------|-------
ionic2          |  3.4.0
angular         | 2
ionic-img-viewer| 2.4.0

**Comment by Riron** [comment]
No there isn't.
I think i need to tweak it a bit in order to get a more "native" feeling. So let me know if you think sensitivity is too high or too low !
Thanks.

**Comment by afcruzs** [comment]
I think it is a little bit too high. furthermore, it would be nice to be able to set the maximum level of zoom programmatically.

If it can be done easily let me know to drop a PR. Thank you for this plugin 👍

**Comment by biskazz** [comment]
I also find the sensitivity too high when the images are zoomed in.

Hoping for a fix. Thanks for the plugin tho. 👍
