### ISSUE TITLE
with ionic2 rc.1 plugin not work

### ISSUE THREAD

**Issue by kadox07** [Riron/ionic-img-viewer#8]
I have read readme.log but plugin not work with ionic2 rc.1. Help me please

**Comment by Riron** [comment]
Hi, thanks for opening an issue.

Have you tried the `1.1.1` version ?
If yes, could you elaborate on what the problem is ?

**Comment by kadox07** [comment]
i update it. Worked :D Sliding function worked in this version?!

**Comment by Riron** [comment]
Great !
No sliding yet, it should come shortly ;)
