### ISSUE TITLE
build with --prod not working

### ISSUE THREAD

**Issue by smkamranqadri** [Riron/ionic-img-viewer#80]
[17:37:27]  ngc started ... 
can't resolve module ./image-viewer-transitions from /home/mkamran/Repositories/waitforme-driver/node_modules/ionic-img-viewer/dist/src/module.d.ts
[17:37:31]  build prod failed: Cannot read property 'registerCustomTransitions' of undefined, resolving symbol 
            IonicImageViewerModule in 
            /home/mkamran/Repositories/waitforme-driver/node_modules/ionic-img-viewer/dist/src/module.d.ts, resolving 
            symbol IonicImageViewerModule in 
            /home/mkamran/Repositories/waitforme-driver/node_modules/ionic-img-viewer/dist/src/module.d.ts 
[WARN] Error occurred during command execution from a CLI plugin (@ionic/cli-plugin-cordova).
Error: Cannot read property 'registerCustomTransitions' of undefined, resolving symbol IonicImageViewerModule in /home/mkamran/Repositories/waitforme-driver/node_modules/ionic-img-viewer/dist/src/module.d.ts, resolving symbol IonicImageViewerModule in /home/mkamran/Repositories/waitforme-driver/node_modules/ionic-img-viewer/dist/src/module.d.ts

### Please provide you version information :
Dependency      |Version
----------------|-------
ionic2          | 2.1.0
angular         | 2.2.1
ionic-img-viewer| 1.3.4

### Have you checked...
- 

- [-] That npm install returns no warning ?
- [-] Doing a purge of your node_modules folder ?

NPM Warnings.

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/watchpack/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN angularfire2@2.0.0-beta.8 requires a peer of rxjs@^5.0.1 but none was installed.
npm WARN @ionic-native/diagnostic@3.10.3 requires a peer of rxjs@^5.0.1 but none was installed.
npm WARN @ionic-native/core@3.7.0 requires a peer of rxjs@^5.0.1 but none was installed.
npm WARN @ionic-native/in-app-browser@4.1.0 requires a peer of rxjs@^5.0.1 but none was installed.
npm WARN @ionic-native/push@3.7.0 requires a peer of rxjs@^5.0.1 but none was installed.
npm WARN @ionic-native/app-version@3.10.3 requires a peer of rxjs@^5.0.1 but none was installed.
npm WARN @ionic-native/local-notifications@4.1.0 requires a peer of rxjs@^5.0.1 but none was installed.
npm WARN @ionic-native/social-sharing@3.14.0 requires a peer of rxjs@^5.0.1 but none was installed.
npm WARN @ionic-native/geolocation@3.14.0 requires a peer of rxjs@^5.0.1 but none was installed.
npm WARN ionic-angular@2.3.0 requires a peer of @angular/common@2.4.8 but none was installed.
npm WARN ionic-angular@2.3.0 requires a peer of @angular/compiler@2.4.8 but none was installed.
npm WARN ionic-angular@2.3.0 requires a peer of @angular/compiler-cli@2.4.8 but none was installed.
npm WARN ionic-angular@2.3.0 requires a peer of @angular/core@2.4.8 but none was installed.
npm WARN ionic-angular@2.3.0 requires a peer of @angular/forms@2.4.8 but none was installed.
npm WARN ionic-angular@2.3.0 requires a peer of @angular/http@2.4.8 but none was installed.
npm WARN ionic-angular@2.3.0 requires a peer of @angular/platform-browser@2.4.8 but none was installed.
npm WARN ionic-angular@2.3.0 requires a peer of @angular/platform-browser-dynamic@2.4.8 but none was installed.
npm WARN ionic-angular@2.3.0 requires a peer of @angular/platform-server@2.4.8 but none was installed.
npm WARN ionic-angular@2.3.0 requires a peer of rxjs@5.0.1 but none was installed.
npm WARN ionic-angular@2.3.0 requires a peer of zone.js@0.7.2 but none was installed.

**Comment by Riron** [comment]
I'm sorry but I won't publish fixes for old versions of the plugin.
If you problem persists, please upgrade to the latest versions of `ionic-img-viewer` & `ionic-angular`

**Comment by SnehaSSD** [comment]
This issue is not solved after upgrading to to latest versions of ionic-img-viewer & ionic-angular
