### ISSUE TITLE
image blinks/jumps when using fullResImage

### ISSUE THREAD

**Issue by parkbroom** [Riron/ionic-img-viewer#81]
`<img #thumbImage [src]="post.image" (click)="presentImage(thumbImage)" />`

  ```
presentImage(thumbImage: HTMLElement): void {
    const imageViewer = this.imageViewerCtrl.create(thumbImage, {
      fullResImage: "assets/images/some-picture.png"
    });
    imageViewer.present();
 }
```

is there a work around for this?

The thumbnail would show first for a split second then the full-size image.  I need it only to show the full-size image

**Comment by Riron** [comment]
There is no blink, it animates from low res to high res. The animation is better that a black screen followed by the high res image suddenly appearing.

To avoid this, pre-load the high res image.
