### ISSUE TITLE
Support for wider screens & desktop

### ISSUE THREAD

**Issue by FelschR** [Riron/ionic-img-viewer#86]
### Please provide you version information :
Dependency      |Version
----------------|-------
ionic2          | 3.9.2
angular         | 4.1.3
ionic-img-viewer| 2.6.1

### Have you checked...
- [x] That npm install returns no warning ?
- [x] Doing a purge of your node_modules folder ?

On wide screens (especially in a desktop browser) I often notice the image being cropped of on the top and bottom. 

I quickly tried a few things and found out that changing the flex-direction of image-viewer.ion-page from `column` to `inherit` or `row` fixes this behavior.
I haven't tried if the zooming capabilities still work on mobile with this change though.

Other optimizations could be made for desktop e.g. showing a zoom slider and being able to drag the image by mouse.

**Comment by Riron** [comment]
Thanks for investigating the problem.
I'll check it out, as I have never seen the problem by myself yet.

About the slider i'm not sure that's really useful, zooming on an image in a dektop is not something we do very often

**Comment by Niavart** [comment]
I second this. I used my App in paysage mode: you can't scroll anymore despite the image not fitting (I can only see a bit of the center). Trying to swipe dismiss the viewer (as soon as I release it). Trying to un-zoom doesn't work.

**Comment by KapelPTronic** [comment]
hallo,

if i am on potrait mode and everything works fine but on landscape mode on Android i have the same issue like @Niavart. see the screens below!! Some solutions so far? 

![screenshot_20171108-141748](https://user-images.githubusercontent.com/15103850/32551231-21caa2c4-c490-11e7-93e1-0ab619ae4d77.png)
![screenshot_20171108-141744](https://user-images.githubusercontent.com/15103850/32551232-21ea14b0-c490-11e7-9724-fc2b54c73cea.png)

**Comment by Riron** [comment]
I'm currently looking at it. `flex-direction: row` works for very big images but break the alignment with smaller images, so it's not ideal.
I'll push a fix shortly hopefully !

**Comment by Riron** [comment]
It should be fixed now, for `ionic-angular > 3.8.0` !
Please try `2.8.0` or `2.9.0` depending on you Ionic version
