### ISSUE TITLE
Image viewer not dismissed on hardware-ware back button [android hardware backbutton]

### ISSUE THREAD

**Issue by manojbhardwaj** [Riron/ionic-img-viewer#87]
Image viewer not dismissed on hardware-ware back button [android hardware backbutton]

**Comment by sharkoz** [comment]
Hi, 
It works fine for me on the latest build.

Maybe you can share some more about your problem ?

**Comment by manojbhardwaj** [comment]
First open image viewer
Image viewer open a modal with zoom in zoom out functionality 
Then try to close image viewer modal with hardware back button  
Image viewer is only close by  Ionic navigation  bar back button not hardware

**Comment by sharkoz** [comment]
This scenario works fine for me. Are you sure you don't have anything else in your app that could impact the default behaviour of the back button ?

**Comment by Riron** [comment]
What version of the plugin are you using ?

**Comment by Riron** [comment]
No answer for a month, closing the issue.
It seems to work fine for every other users. If not, feel free to comment !
