### ISSUE TITLE
Doesn't work when using --prod

### ISSUE THREAD

**Issue by shadoWalker89** [Riron/ionic-img-viewer#94]
### Please provide you version information :
Dependency      |Version
----------------|-------
ionic          | 3.7.1
angular         | 4.4.3
ionic-img-viewer| 2.7.3

### Have you checked...
- [X] That npm install returns no warning ?
- [ ] Doing a purge of your node_modules folder ?

When building the app using the --prod flag when i click on the image it doesn't open the image modal and i get his warning in the console

```js
[Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
O @ polyfills.js:2
t.scheduleTask @ polyfills.js:3
r.scheduleTask @ polyfills.js:3
r.scheduleEventTask @ polyfills.js:3
(anonymous) @ polyfills.js:2
t.registerListener @ vendor.js:1
t @ vendor.js:1
t.pointerEvents @ vendor.js:1
t.listen @ vendor.js:1
e @ vendor.js:1
(anonymous) @ vendor.js:1
t.invoke @ polyfills.js:3
r.run @ polyfills.js:3
t.runOutsideAngular @ vendor.js:1
e.ngOnInit @ vendor.js:1
Mn @ vendor.js:1
lr @ vendor.js:1
cr @ vendor.js:1
Pr @ vendor.js:1
(anonymous) @ vendor.js:1
updateDirectives @ vendor.js:1
ar @ vendor.js:1
t.detectChanges @ vendor.js:1
e._viewAttachToDOM @ vendor.js:1
e._transition @ vendor.js:1
(anonymous) @ vendor.js:1
t.invoke @ polyfills.js:3
onInvoke @ vendor.js:1
t.invoke @ polyfills.js:3
r.run @ polyfills.js:3
(anonymous) @ polyfills.js:3
t.invokeTask @ polyfills.js:3
onInvokeTask @ vendor.js:1
t.invokeTask @ polyfills.js:3
r.runTask @ polyfills.js:3
o @ polyfills.js:3
e.invokeTask @ polyfills.js:3
p @ polyfills.js:2
v @ polyfills.js:2
```

**Comment by Riron** [comment]
I wasn't able to reproduce the problem yet. You were using the classic directive ?

**Comment by shadoWalker89** [comment]
Yeah i used the directive on the <img/>

**Comment by cnpallares** [comment]
Hello,
Im dealing with the same issue only on Android. In previous releases of my app, the plugin worked perfectly. I have the same version information than @shadoWalker89.
Im trying to debug the cause..
;)

**Comment by shadoWalker89** [comment]
@cnpallares sorry to answer so late, but i ended up using this native plugin https://ionicframework.com/docs/native/photo-viewer/
