### ISSUE TITLE
how to show image viewer when on icon click in ionic 2

### ISSUE THREAD

**Issue by ravi-pandit14** [Riron/ionic-img-viewer#95]
### Please provide you version information :
Dependency      |Version
----------------|-------
ionic2          | 
angular         |
ionic-img-viewer|

### Have you checked...
- [x] That npm install returns no warning ?
- [x] Doing a purge of your node_modules folder ?

**Comment by Riron** [comment]
Read the README: **Usage** -> **Programmatic usage** :wink:
If your image is not yet in the DOM, [create an image element and set the src](https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/Image)
