### ISSUE TITLE
support tap backdrop dismiss attr in directive?

### ISSUE THREAD

**Issue by jasonz1987** [Riron/ionic-img-viewer#98]
there is  a little problem when i use this plugin.

i suggest the image-viewer  will dismiss  if  i tap the backdrop.

i also saw `enableBackdropDismiss ` atrr in `ImageViewerOptions`,but there is not attr to config it when i use imgViewere directive.

so any ideas?

@Riron

**Comment by Riron** [comment]
I just added support for it.
Please try `2.8.0` or `2.9.0` depending on you Ionic version
